version: '3.6'
services:
 mdb:
   image: mysql:5.7
   platform: linux/amd64
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: example
   ports:
     - 6543:5432
   volumes:
     - ./db-data:/var/lib/postgresql/data
     - ./db.sql:/docker-entrypoint-initdb.d/db.sql
 
 adminer:
   image: adminer
   depends_on:
     - mdb
   restart: always
   ports:
     - 8080:8080
 pgadmin:
   image: dpage/pgadmin4
   depends_on:
     - mdb
   ports:
     - 7070:80
   environment:
     PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
     PGADMIN_DEFAULT_PASSWORD: admin
   restart: unless-stopped
